# version: '3.8' # Specify Docker Compose version
services:
  mailpit: # Name of your Mailpit service
    image: axllent/mailpit:latest # Official Mailpit image
    container_name: mailpit # Custom name for the container
    ports: # Map container ports to host ports
      - 8025:8025  # Web UI (adjust if needed)
      - 1025:1025  # SMTP Server (adjust if needed)
    volumes: # Persist data (optional)
      - ./mailpit-data:/data # Store emails and settings
    environment: # Additional settings (optional)
      - TZ=Asia/Jakarta # Set timezone to WIB
      # - MP_SMTP_AUTH=plain # Enable SMTP authentication
      # - MP_UI_HTTPS=true # Enable HTTPS for the web UI
      # ... (see Mailpit documentation for more options)
